---
- name: Upload firmware
  local_action: command scp "{{firmware_path}}/gluon-ffhb-{{firmware_new}}-{{ image_name }}-sysupgrade.bin" "[{{ ansible_ssh_host }}]":/tmp/firmware.bin

- name: Upgrade firmware
  raw: "wait 30; sysupgrade -n /tmp/firmware.bin"
