---
- name: Upload firmware
  action: copy_unsafe src={{firmware_path}}/sysupgrade/gluon-ffhb-{{firmware_new}}-{{ model.stdout.strip().replace(" ","-").lower() }}-sysupgrade.bin dest=/tmp/sysupgrade.bin

- name: Install nohup
  raw: opkg update && opkg install coreutils-nohup

- name: Upgrade firmware
  raw: nohup sysupgrade -n /tmp/sysupgrade.bin&
