---
- name: Upload firmware
  action: scp src={{firmware_path}}/sysupgrade/gluon-ffhb-{{firmware_new}}-{{ hardware.model.strip().replace(" ","-").lower() }}-sysupgrade.bin dest=/tmp/sysupgrade.bin

- name: Upgrade firmware
  raw: sysupgrade -n /tmp/sysupgrade.bin
