---
- name: Upload firmware
  action: copy_unsafe src={{firmware_path}}/sysupgrade/gluon-ffhb-2015.1.1+breminale3-{{ model.stdout.strip().replace(" ","-").lower() }}-sysupgrade.bin dest=/tmp/sysupgrade.bin

- name: Upgrade firmware
  raw: sysupgrade -n /tmp/sysupgrade.bin
