#!/usr/bin/lua
#
# Enables or disables bremen.freifunk.net depending on
# whether the gateway is reachable
#

uci = require("uci").cursor()

gateway   = "2a00:c380:dead::1"
ssid      = "bremen.freifunk.net"
ping      = os.execute("ping6 -c 2 "..gateway)
reachable = ping==0
enabled   = uci:get("wireless", "client_radio0", "disabled") ~= "1"

if reachable ~= enabled then
  print("state changed")

  uci:foreach("wireless", "wifi-iface",
    function(s)
      if s['ssid'] == ssid then
        uci:set("wireless", s['.name'], "disabled", reachable and '0' or '1')
      end
  end)

  uci:commit("wireless")
  os.execute("wifi")
end
