#!/usr/bin/env python2
#
# Dynamic inventory script that uses a IPv6 multicast ping
# to discover hosts in the current network.
#
# $ ansible nodes -m sh_ping -i nodes-link-local
#

import json
import re
import os
import subprocess

iface = "br-ffhb"
output   = subprocess.check_output(["ping","-6","ff02::1%"+iface,"-Lnc 2"])
nodes    = []
hostvars = {}

for host in re.findall('from ([\da-f:]+)%'+iface+': ', output):
  name = host.split("fe80::",2)[1].replace(":","")
  nodes.append(name)
  hostvars[name] = {
    "ansible_ssh_host": host+"%"+iface,
  }


print json.dumps({"nodes": {"hosts": nodes}, "_meta": {"hostvars": hostvars}})
