#!/usr/bin/env python2
#
# Dynamic inventory script for ansible
#
# $ ansible nodes -m sh_ping -i nodes
#

from sys import path
path.append("lib")

import hosts
import json

print json.dumps(hosts.load())
