---
- name: Set hostname
  uci: command=set key=gluon-node-info.@owner[0].hostname value={{node_name.replace(\" \",\"-\")}}"
  tags: hostname
  when: node_name is defined

- name: Update hostname
  raw: "echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname"
  tags: hostname
  when: node_name is defined

- name: Change owner
  uci: command=set key=gluon-node-info.@owner[0].contact value={{owner}}
  tags: owner
  when: owner is defined




- name: Set position latitude
  uci: command=set key=gluon-node-info.@location[0].latitude value={{geo_latitude}}
  tags: location
  when: geo_latitude is defined

- name: Set position longitude
  uci: command=set key=gluon-node-info.@location[0].longitude value={{geo_longitude}}
  tags: location
  when: geo_longitude is defined

- name: Enable position
  uci: command=set key=gluon-node-info.@location[0].share_location value=1
  tags: location
  when: geo_latitude is defined or geo_longitude is defined

- name: Save position
  raw: "uci commit gluon-node-info"
  tags: location
  when: geo_latitude is defined or geo_longitude is defined



- name: apply wifi24 txpower
  uci: command=set key=wireless.radio0.txpower value={{radio24_txpower}}
  tags:
    - radio24
    - txpower
    - wifi
  when: radio24_txpower is defined

- name: apply wifi24 channel
  uci: command=set key=wireless.radio0.channel value={{radio24_channel}}
  tags:
    - radio24
    - channel
    - wifi
  when: radio24_channel is defined

- name: apply wifi5 txpower
  uci: command=set key=wireless.radio1.txpower value={{radio5_txpower}}
  tags:
    - radio5
    - txpower
    - wifi
  when: radio5_txpower is defined

- name: apply wifi5 channel
  uci: command=set key=wireless.radio1.channel value={{radio5_channel}}
  tags:
    - radio5
    - channel
    - wifi
  when: radio5_channel is defined


- name: Save position
  raw: "wifi"
  tags:
  - radio5
  - radio24
  - wifi
  - channel
  - txpower
  when: radio24_txpower is defined or radio24_channel is defined or radio5_txpower is defined or radio5_channel is defined
