# Configure PoE passthrough
---
- name: Fetch gluon facts
  gluon: facts

- fail: msg="unsupported model"
  when: '"TP-Link CPE" not in hardware.model'

- name: Upload init script
  action: scp src=poe dest=/etc/init.d/

- name: Enable poe
  raw: /etc/init.d/poe enable

- name: Start poe
  raw: /etc/init.d/poe start
