#!/bin/sh /etc/rc.common
# Enables PoE Passthrough on TL-CPE2XX/CPE5XX
# http://wiki.openwrt.org/toh/tp-link/tl-cpe210#poe_passthrough

START=10
STOP=15

start() {
  echo 20  > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio20/direction
  echo 1   > /sys/class/gpio/gpio20/value
}

stop() {
  echo 0   > /sys/class/gpio/gpio20/value
}
