---
- name: uci commit
  raw: uci commit

- name: update hostname
  raw: "echo $(uci get system.@system[0].hostname) > /proc/sys/kernel/hostname"

- name: restart wifi
  raw: wifi

- name: restart log
  raw: /etc/init.d/log restart
