---
- name: Set hostname
  uci: command=set key=system.@system[0].hostname value="{{node_name_prefix}}{{node_name}}"
  notify: update hostname
  tags: hostname
  when: node_name is defined

- name: Change owner
  uci: command=set key=gluon-node-info.@owner[0].contact value={{owner}}
  tags: owner
  when: owner is defined




- name: Set position latitude
  uci: command=set key=gluon-node-info.@location[0].latitude value={{geo_latitude}}
  tags: location
  when: geo_latitude is defined

- name: Set position longitude
  uci: command=set key=gluon-node-info.@location[0].longitude value={{geo_longitude}}
  tags: location
  when: geo_longitude is defined

- name: Enable position
  uci: command=set key=gluon-node-info.@location[0].share_location value=1
  tags: location
  when: geo_latitude is defined or geo_longitude is defined

- name: Save position
  raw: "uci commit gluon-node-info"
  tags: location
  when: geo_latitude is defined or geo_longitude is defined



- name: apply wifi24 mesh
  uci: command=set key=wireless.ibss_radio0.disabled value={{radio24_mesh_disabled}}
  notify: restart wifi
  tags:
    - radio24
    - mesh
    - wifi
  when: radio24_mesh_defined is defined

- name: apply wifi24 txpower
  raw: iw dev client0 set txpower fixed {{radio24_txpower}}.0
  tags:
    - radio24
    - txpower
    - wifi
  when: radio24_txpower is defined

- name: apply wifi24 channel
  uci: command=set key=wireless.radio0.channel value={{radio24_channel}}
  notify: restart wifi
  tags:
    - radio24
    - channel
    - wifi
  when: radio24_channel is defined


- name: apply wifi5 mesh
  uci: command=set key=wireless.ibss_radio0.disabled value={{radio5_mesh_disabled}}
  notify: restart wifi
  tags:
    - radio5
    - mesh
    - wifi
  when: radio5_mesh_disabled is defined

- name: apply wifi5 txpower
  raw: iw dev client1 set txpower fixed {{radio5_txpower}}.0
  tags:
    - radio5
    - txpower
    - wifi
  when: radio5_txpower is defined

- name: apply wifi5 channel
  uci: command=set key=wireless.radio1.channel value={{radio5_channel}}
  notify: restart wifi
  tags:
    - radio5
    - channel
    - wifi
  when: radio5_channel is defined
