---
- name: Set hostname
  raw: uci set system.@system[0].hostname="{{node_name}}.{{node_name_suffix}}"; uci commit system
  notify: update hostname
  tags: hostname
  when: node_name is defined

- name: Change owner
  raw: uci set gluon-node-info.@owner[0].contact="{{owner}}"
  tags: owner
  when: owner is defined


- name: set syslog
  raw: uci set system.@system[0].log_ip="{{syslog}}"
  notify: restart log
  tags: syslog
  when: syslog is defined

- name: Set position latitude
  raw: uci set gluon-node-info.@location[0].latitude="{{geo_latitude}}"
  tags: location
  when: geo_latitude is defined

- name: Set position longitude
  raw: uci set gluon-node-info.@location[0].longitude="{{geo_longitude}}"
  tags: location
  when: geo_longitude is defined

- name: Enable position
  raw: uci set gluon-node-info.@location[0].share_location=1
  tags: location
  when: geo_latitude is defined or geo_longitude is defined

- name: Save position
  raw: "uci commit gluon-node-info"
  tags: location
  when: geo_latitude is defined or geo_longitude is defined



- name: apply wifi24 mesh
  raw: uci set wireless.ibss_{{radio24}}.disabled="{{radio24_mesh_disabled}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio24
    - mesh
    - wifi
  when: radio24_mesh_disabled is defined

- name: apply wifi24 client
  raw: uci set wireless.client_{{radio24}}.disabled="{{radio24_client_disabled}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio24
    - client
    - wifi
  when: radio24_client_disabled is defined

- name: apply wifi24 txpower
  raw: uci set wireless.{{radio24}}.txpower="{{radio24_txpower}}"; uci commit wireless
  tags:
    - radio24
    - txpower
    - wifi
  when: radio24_txpower is defined

- name: apply wifi24 channel
  raw: uci set wireless.{{radio24}}.channel="{{radio24_channel}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio24
    - channel
    - wifi
  when: radio24_channel is defined


- name: apply wifi5 mesh
  raw: uci set wireless.ibss_{{radio5}}.disabled="{{radio5_mesh_disabled}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio5
    - mesh
    - wifi
  when: radio5_mesh_disabled is defined

- name: apply wifi5 client
  raw: uci set wireless.client_{{radio5}}.disabled="{{radio5_client_disabled}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio5
    - client
    - wifi
  when: radio5_client_disabled is defined

- name: apply wifi5 txpower
  raw: uci set wireless.{{radio5}}.txpower="{{radio5_txpower}}"; uci commit wireless
  tags:
    - radio5
    - txpower
    - wifi
  when: radio5_txpower is defined

- name: apply wifi5 channel
  raw: uci set wireless.{{radio5}}.channel="{{radio5_channel}}"; uci commit wireless
  notify: restart wifi
  tags:
    - radio5
    - channel
    - wifi
  when: radio5_channel is defined
