# Configure radios
---
- name: apply wifi24 channel
  uci: set wireless.radio0.channel={{radio24_channel}}
  notify:
  - restart wifi

- name: apply wifi24 txpower
  uci: set wireless.radio0.txpower=0
  tags: txpower
  notify:
  - restart wifi

- name: apply wifi5 txpower
  uci: set wireless.radio1.txpower=15
  tags: txpower
  notify:
  - restart wifi

- name: apply wifi5 channel
  uci: set wireless.radio1.channel={{radio5_channel}}
  notify:
  - restart wifi

- name: apply wifi5 htmode
  uci: set wireless.radio1.htmode=HT20
  tags: htmode
  notify:
  - restart wifi

- name: apply wifi regdom
  raw: iw reg set US
  tags: regdom
  notify:
  - restart wifi

- name: apply wifi5 country
  uci: set wireless.radio1.country=US
  tags: htmode
  notify:
  - restart wifi

- name: primary mgmt network 5ghz only
  uci: set wireless.mgmt_radio0.ssid=mgmt.ffhb.de-legacy
  tags: mgmt
  notify:
  - restart wifi

