---
- name: Install Packages
  action: apt pkg={{item}}
  with_items:
  - apache2-mpm-worker
  - apt-transport-https

- name: Add phusion key
  apt_key: keyserver='keyserver.ubuntu.com' id=16378A33A6EF16762922526E561F9B9CAC40B2F7

- name: Add phusion repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'

- name: Install passenger
  action: apt pkg=libapache2-mod-passenger

- name: Enable passenger
  apache2_module: state=present name=passenger
