# ansible-playbook playbooks/nodes-fetch-infos.yml -i nodes -e "passphrase=MYSECRET"
---
- hosts: nodes
  gather_facts: no
  tasks:
  - uci: get_sections wireless.wifi-device
    register: radios

  - debug: var=radios.radio0.channel
  - debug: var=radios.radio1.channel

  - local_action: uri url=http://monitoring2.breminale.ffhb.de/api/ method=POST body="passphrase={{passphrase}}&mac={{inventory_hostname}}&radio24_channel={{radios.radio0.channel}}&radio24_txpower={{radios.radio0.txpower}}&radio5_channel={{radios.radio1.channel}}&radio5_txpower={{radios.radio1.txpower}}" HEADER_Content-Type="application/x-www-form-urlencoded"
