# restart respondd if not running
---
- hosts: nodes
  gather_facts: no
  tasks:
  - raw: "pgrep respondd"
    register: pgrep
    ignore_errors: yes

  #show data
  - debug: var=pgrep.rc 

  - raw: /etc/init.d/gluon-respondd restart
    when: pgrep.rc != 0
